### ISSUE TITLE
SmartRefreshLayout改成最新版本，ViewPager显示不全

### ISSUE THREAD

**Issue by GillX** [SiberiaDante/MultiScrollDemo#11]
你好，谢谢你的开源
请教下SmartRefreshLayout:1.1.0-alpha-12，该demo的ViewPager显示不全，该怎么调整呢？

**Comment by SiberiaDante** [comment]
alpha不是稳定版，不建议项目中使用，另外1.1.0-alpha-12中OnMultiPurposeListener的接口有变动，所以最好还是采用稳定版本1.0.4-4
