### ISSUE TITLE
部分机型头部点击事件无反应或反映迟钝

### ISSUE THREAD

**Issue by oyl1love** [SiberiaDante/MultiScrollDemo#13]
如pixelxl2，华为p20，以及部分老机型都有类似问题

**Comment by ruanbaojun1105** [comment]
return !(xDistance >= yDistance || yDistance < scaledTouchSlop) && isNeedScroll;
把JudgeNestedScrollView这个控件的事件拦截改一下

**Comment by oyl1love** [comment]
多谢大佬，完美解决
