### ISSUE TITLE
ScrollView 滑动问题

### ISSUE THREAD

**Issue by lost24** [SiberiaDante/MultiScrollDemo#8]
先谢谢了  我的项目结构和你基本一致 ，有问题请教一下，当mScrollView.setNeedScroll(false); 设置为false后 ,onScrollChange 都不再回调了 ，下次设置setNeedScroll(true) 怎么触发的  ，你的demo是好的  但我这边有问题，找不到原因

**Comment by SiberiaDante** [comment]
不好说啊，是不是你NestedScrollView 的拦截处理有问题？

**Comment by LXLYHM** [comment]
遇到跟楼主一样的问题呀，楼主最后有解决了吗？除了API版本，我也看不出我的代码跟demo有啥区别，但是demo行，我的就是不行，因为设置为false后 ,onScrollChange 都不再回调了
